<?php

/**
 * @file
 * Module file for the Tieto Media Library entioty browser.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function filefield_sources_jsonapi_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.filefield_sources_jsonapi':
      return check_markup(file_get_contents(dirname(__FILE__) . '/README.md'));
  }
}

/**
 * Implements hook_theme().
 */
function filefield_sources_jsonapi_theme($existing, $type, $theme, $path) {
  return [
    'browser_media_box' => [
      'variables' => [
        'checkbox' => [],
        'checkbox_id' => '',
        'img' => [],
        'title' => '',
      ],
    ],
  ];
}
