filefield_sources_jsonapi.filefield_sources_jsonapi.*:
  type: config_entity
  label: 'JSON API file field source config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: string
      label: 'Label'
    apiUrl:
      type: string
      label: 'JSON API Url'
    params:
      type: string
      label: 'Params'
    urlAttributePath:
      type: string
      label: 'URL attribute path'
    thumbnailUrlAttributePath:
      type: string
      label: 'Thumbnail URL attribute path'
    titleAttributePath:
      type: string
      label: 'Title attribute path'
    altAttributePath:
      type: string
      label: 'Alt attribute path'
    sortOptionList:
      type: string
      label: 'Sorting option list'
    searchFilter:
      type: string
      label: 'Search filter attribute name'
    itemsPerPage:
      type: string
      label: 'Items to display'
    basicAuthentication:
      type: boolean
      label: 'Basic authentication'
    uuid:
      type: string
